type User {
  id: ID!
  googleID: ID
  facebookID: ID
  email: String
  username: String
  photo: String
  firstName: String
  lastName: String
  comments: [Comment!]
}

type AccessInfo {
  accessToken: String!
  refreshToken: String!
}

input SignInInput {
  account: String!
  password: String!
}

input AddUserInput {
  email: String!
  password: String!
  username: String!
}

input PatchUserInput {
  username: String
  photo: String
  firstName: String
  lastName: String
}

extend type Query {
  me: User!
  signIn (data: SignInInput!): AccessInfo! 
}

extend type Mutation {
  addUser (data: AddUserInput!): AccessInfo!
  patchMe (data: PatchUserInput!): User!
  deleteMe (password: String): Boolean
}